# Generated by Django 6.0.7 on 2026-08-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(default='FactoryFlow Industries', max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(choices=[('NPR', 'Nepalese Rupee (NPR)'), ('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)')], default='NPR', max_length=3)),
                ('date_format', models.CharField(choices=[('d M Y', 'DD Mon YYYY  (06 Aug 2026)'), ('d/m/Y', 'DD/MM/YYYY   (06/08/2026)'), ('m/d/Y', 'MM/DD/YYYY   (08/06/2026)'), ('Y-m-d', 'YYYY-MM-DD   (2026-08-06)')], default='d M Y', max_length=10)),
                ('invoice_prefix', models.CharField(blank=True, default='INV-', max_length=10)),
                ('batch_prefix', models.CharField(blank=True, default='BATCH-', max_length=10)),
                ('default_tax_percent', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('auto_logout_minutes', models.PositiveIntegerField(default=30, help_text='Minutes of inactivity before logout. 0 disables auto-logout.')),
            ],
            options={
                'verbose_name': 'Factory settings',
                'verbose_name_plural': 'Factory settings',
            },
        ),
    ]
