# Generated by Django 6.0.7 on 2026-07-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Expense categories'},
        ),
    ]
