# Generated by Django 6.0.7 on 2026-07-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_product_brand_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch_no', models.CharField(max_length=30, unique=True)),
                ('supervisor', models.CharField(max_length=120)),
                ('machine', models.CharField(choices=[('cutting', 'Cutting'), ('stitching', 'Stitching'), ('assembly', 'Assembly'), ('finishing', 'Finishing')], default='cutting', max_length=15)),
                ('target_quantity', models.PositiveIntegerField()),
                ('produced_quantity', models.PositiveIntegerField(default=0)),
                ('defective_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('running', 'Running'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='products.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
