# Generated by Django 6.0.7 on 2026-07-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='total_spend',
        ),
    ]
